language: generic
sudo: required
services:
  - docker

before_install:
  - docker pull ubuntu
  - docker run --name ubuntu -it -d ubuntu /bin/bash
env:
  - PLATFORM=unix
  - PLATFORM=win
  - PLATFORM=android

script:
  - docker exec ubuntu apt-get -qq update
  - docker exec ubuntu apt-get -qq -y dist-upgrade
  - docker exec ubuntu apt-get -qq -y install build-essential git libgl1-mesa-dev libz-mingw-w64-dev g++-mingw-w64-x86-64 zlib1g-dev flex bison wget unzip python
  - docker exec ubuntu wget -q https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip
  - docker exec ubuntu unzip -qq android-ndk-r12b-linux-x86_64.zip
  - docker exec ubuntu ./android-ndk-r12b/build/tools/make_standalone_toolchain.py --arch arm --api 18 --install-dir /mychain
  - docker exec ubuntu git clone --depth 25 -b $TRAVIS_BRANCH https://github.com/loganmc10/GLupeN64.git
  - docker exec ubuntu /bin/bash -c "export PATH=$PATH:/mychain/bin; cd GLupeN64; git checkout $TRAVIS_COMMIT; platform=$PLATFORM make" 
